# Generated by Django 3.2.5 on 2021-07-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionResults',
            fields=[
                ('market_name', models.CharField(help_text='Market Name', max_length=32, null=True)),
                ('delivery_date', models.DateField(help_text='Delivery Date', null=True)),
                ('unique_bid_number', models.CharField(help_text='Unique bid number', max_length=128, primary_key=True, serialize=False)),
                ('response_unit', models.CharField(help_text='Response Unit', max_length=64, null=True)),
                ('unit_type', models.CharField(help_text='Unit type', max_length=16, null=True)),
                ('agent_applicant', models.CharField(help_text='Agent/Applicant', max_length=128, null=True)),
                ('related_entity', models.CharField(help_text='Related Entity', max_length=128, null=True)),
                ('volume_offered', models.IntegerField(help_text='Volume offered', null=True)),
                ('volume_accepted', models.IntegerField(help_text='Volume Accepted', null=True)),
                ('delivery_start', models.DateTimeField(help_text='Delivery Start', null=True)),
                ('delivery_end', models.DateTimeField(help_text='Delivery End', null=True)),
                ('service_duration', models.IntegerField(help_text='Service Duration', null=True)),
                ('availability_fee', models.DecimalField(decimal_places=2, help_text='Availability Fee', max_digits=18, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total Cost', max_digits=18, null=True)),
                ('rtm_no_rtm', models.CharField(help_text='RTM/no RTM', max_length=64, null=True)),
                ('accepted_rejected', models.CharField(help_text='Accepted/Rejected', max_length=128, null=True)),
                ('rejection_code', models.CharField(help_text='Rejection code', max_length=128, null=True)),
                ('technology_type', models.CharField(help_text='Technology Type', max_length=128, null=True)),
                ('rank_delivery_date', models.FloatField(help_text='rank Delivery Date', null=True)),
                ('rank_agent_applicant', models.FloatField(help_text='rank Agent/Applicant', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('auction_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='tender.auctionresults')),
            ],
        ),
    ]
